{
 "title": "Ceph Prod",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "query": "SHOW TAG VALUES  FROM /^ceph.*$/ WITH KEY = \"cluster_name\"  WHERE cluster_name   =~ /^.*$/ "
   }
  ]
 },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upload Time (<1MB)",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ceph_upload",
     "query": "SELECT count(\"request_time\"),min(\"request_time\"),max(\"request_time\"),mean(\"request_time\"),percentile(\"request_time\", 99),percentile(\"request_time\", 90),percentile(\"request_time\", 50) FROM \"nginx_upload_log\" WHERE (\"request_length\" < 1000000 AND \"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "API Status (404 excluded)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "2xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_ceph_nginx",
     "query": "SELECT count(\"status\") FROM \"nginx_access_log\" WHERE \"http_method\" != 'HEAD' AND \"uri\" != '/auth/1.0' AND \"status\" >= 200 AND \"status\" < 300 AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "3xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_ceph_nginx",
     "query": "SELECT count(\"status\") FROM \"nginx_access_log\" WHERE \"http_method\" != 'HEAD' AND \"uri\" != '/auth/1.0' AND \"status\" >= 300 AND \"status\" < 400 AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "4xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"nginx_access_log\" WHERE \"http_method\" != 'HEAD' AND \"uri\" != '/auth/1.0' AND \"status\" >= 400 AND \"status\" < 500 AND \"status\" != 404 AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"nginx_access_log\" WHERE \"http_method\" != 'HEAD' AND \"uri\" != '/auth/1.0' AND \"status\" >= 500 AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "GET (<1MB)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(request_time) FROM \"nginx_download_log\" WHERE (\"body_bytes_sent\"<=1000000) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Delete",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(request_time) FROM \"nginx_delete_log\" WHERE $timeFilter AND \"cluster_name\" =~ /^$cluster_name$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PUT (<1MB objects)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(request_time) FROM \"nginx_upload_log\" WHERE (\"request_length\"<=1024000) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "List Count & Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "List Count / Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"http_method\") FROM \"nginx_access_log\" WHERE \"http_method\"='GET' AND (\"uri\" =~ /\\?.*/) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "List Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"request_time\") FROM \"nginx_access_log\" WHERE \"http_method\"='GET' AND (\"uri\" =~ /\\?.*/) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Time (<1MB)",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ceph_upload",
     "query": "SELECT count(\"request_time\"),min(\"request_time\"),max(\"request_time\"),mean(\"request_time\"),percentile(\"request_time\", 99),percentile(\"request_time\", 90),percentile(\"request_time\", 50) FROM \"nginx_download_log\" WHERE (\"body_bytes_sent\" < 1000000 AND \"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Upload/Download BW (One Node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_ceph_nginx_2",
     "query": "SELECT sum(\"body_bytes_sent\") / sum(\"request_time\") * 8 FROM \"nginx_download_log\" WHERE  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter  GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"request_length\") / sum(\"request_time\") * 8 FROM \"nginx_upload_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter  GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload Requests Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_ceph_nginx",
     "query": "SELECT count(\"status\") FROM \"nginx_upload_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY \"host_ip\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Requests Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_ceph_nginx",
     "query": "SELECT count(\"status\") FROM \"nginx_download_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY \"host_ip\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per-Bucket Upload/Download BW (One Node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "alias": "$tag_bucket Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_ceph_nginx_2",
     "query": "SELECT sum(\"body_bytes_sent\") / sum(\"request_time\") * 8 FROM \"nginx_download_log\" WHERE  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter  GROUP BY time(5m),\"bucket\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_bucket Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"request_length\") / sum(\"request_time\") * 8 FROM \"nginx_upload_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter  GROUP BY time(5m),\"bucket\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload Size Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "<1M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"request_length\") FROM \"nginx_upload_log\" WHERE (\"request_length\" >= 0 AND \"request_length\" < 1000000) AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "1~2M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"request_length\") FROM \"nginx_upload_log\" WHERE  (\"request_length\" >= 1000000 AND \"request_length\" < 2000000)  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "2~5M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"request_length\") FROM \"nginx_upload_log\" WHERE  (\"request_length\" >= 2000000 AND \"request_length\" < 5000000)  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5~100M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"request_length\") FROM \"nginx_upload_log\" WHERE  (\"request_length\" >= 5000000 AND \"request_length\" < 100000000)  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "100M~1G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"request_length\") FROM \"nginx_upload_log\" WHERE  (\"request_length\" >= 100000000 AND \"request_length\" < 1000000000)  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "1G+",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"request_length\") FROM \"nginx_upload_log\" WHERE  \"request_length\" >= 1000000000  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Size Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "<1M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"body_bytes_sent\") FROM \"nginx_download_log\" WHERE (\"body_bytes_sent\" >= 0 AND \"body_bytes_sent\" < 1000000) AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "1~2M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"body_bytes_sent\") FROM \"nginx_download_log\" WHERE  (\"body_bytes_sent\" >= 1000000 AND \"body_bytes_sent\" < 2000000)  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "2~5M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"body_bytes_sent\") FROM \"nginx_download_log\" WHERE  (\"body_bytes_sent\" >= 2000000 AND \"body_bytes_sent\" < 5000000)  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5~100M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"body_bytes_sent\") FROM \"nginx_download_log\" WHERE  (\"body_bytes_sent\" >= 5000000 AND \"body_bytes_sent\" < 100000000)  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "100M~1G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"body_bytes_sent\") FROM \"nginx_download_log\" WHERE  (\"body_bytes_sent\" >= 100000000 AND \"body_bytes_sent\" < 1000000000)  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "1G+",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"body_bytes_sent\") FROM \"nginx_download_log\" WHERE  \"body_bytes_sent\" >= 1000000000  AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload/Download/Delete Count Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\")/300 FROM \"nginx_upload_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\")/300 FROM \"nginx_download_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Delete",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\")/300 FROM \"nginx_delete_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Slow Upload (4K~1M)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\")/300 FROM \"nginx_upload_log\" WHERE (\"request_length\" > 4095 AND \"request_length\" < 1024000 AND \"request_time\" > 0.200) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Slow Download (4K~1M)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\")/300 FROM \"nginx_download_log\" WHERE (\"body_bytes_sent\" > 4095 AND \"body_bytes_sent\" < 1024000 AND \"request_time\" > 0.200) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Error Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "4xx and 5xx Responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "4xx (except 404)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"nginx_access_log\" WHERE (\"status\" >= 400 AND \"status\" <500 AND \"status\" != 404) AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"nginx_access_log\" WHERE (\"status\" >= 500) AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "404",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"nginx_access_log\" WHERE (\"status\" = 404) AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4xx (except 404)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"nginx_access_log\" WHERE \"status\" >= 400 AND \"status\" != 404 AND \"status\" < 500 AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY \"host_ip\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "5xx",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"nginx_access_log\" WHERE \"status\" >= 500 AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY \"host_ip\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4xx Responses (exclude 404)",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_ceph_nginx",
     "query": "SELECT \"http_method\", \"status\", \"request_length\", \"body_bytes_sent\", \"request_time\", \"remote_addr\", \"http_x_forwarded_for\", \"host_ip\", \"uri\"  FROM \"nginx_access_log\" WHERE (\"status\" >= 400 AND \"status\"!=404) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter  LIMIT 500",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "5xx Responses",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_ceph_nginx",
     "query": "SELECT \"http_method\", \"status\", \"request_length\", \"body_bytes_sent\", \"request_time\", \"remote_addr\", \"http_x_forwarded_for\", \"host_ip\", \"uri\"  FROM \"nginx_access_log\" WHERE (\"status\" >= 500) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter  LIMIT 500",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slow Uploads/Downloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Upload Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 27 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "alias": "$tag_host_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"status\") FROM \"nginx_upload_log\" WHERE (\"request_length\" < 1000000 AND \"request_time\" > 0.100 ) AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY \"host_ip\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Slow Upload",
     "type": "graph",
     "gridPos": { "h": 5, "w": 17, "x": 7, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_bucket",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"status\") FROM \"nginx_upload_log\" WHERE (\"request_length\" < 1000000 AND \"request_time\" > 0.100 ) AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time(5m),\"bucket\" ORDER BY DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Slow Download Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 32 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "alias": "$tag_host_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"status\") FROM \"nginx_download_log\" WHERE (\"body_bytes_sent\" < 1000000 AND \"request_time\" > 0.100 ) AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY \"host_ip\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Slow Download",
     "type": "graph",
     "gridPos": { "h": 5, "w": 17, "x": 7, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_bucket",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"status\") FROM \"nginx_download_log\" WHERE (\"body_bytes_sent\" < 1000000 AND \"request_time\" > 0.100 ) AND \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter GROUP BY time(5m),\"bucket\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Slow Uploads",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "test_ceph_nginx",
       "query": "SELECT \"status\", \"request_length\",\"request_time\", \"remote_addr\", \"http_x_forwarded_for\", \"host_ip\",\"bucket\",\"file\"  FROM \"nginx_upload_log\" WHERE (\"request_length\" < 1000000 AND \"request_time\" > 0.200 ) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter  LIMIT 500",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Slow Downloads",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "test_ceph_nginx",
       "query": "SELECT \"status\",\"body_bytes_sent\", \"request_time\",\"remote_addr\", \"http_x_forwarded_for\", \"host_ip\",\"bucket\",\"file\"  FROM \"nginx_download_log\" WHERE (\"body_bytes_sent\" < 1000000 AND \"request_time\" > 0.100 ) AND  \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter  LIMIT 500",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Internal Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS (ceph version < 12)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Total IOPS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"op_per_sec\") FROM \"ceph_pgmap\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Max IOPS (Estimated)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"num_osds\") *100/3/2 FROM \"ceph_osdmap\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "IOPS (ceph version = 12)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Write",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"write_op_per_sec\") FROM \"ceph_pgmap\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Max Write (Estimation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"num_osds\") *100/3/2 FROM \"ceph_osdmap\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Read",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"read_op_per_sec\") FROM \"ceph_pgmap\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Max Read (Estimation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"num_osds\") *100/3 FROM \"ceph_osdmap\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Objects Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 4 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"objects\") FROM \"ceph_pool_usage\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Usage Growth",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"total_used_bytes\") FROM \"ceph_usage\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time(5m)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OSD Perf (Latency)",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
     "targets": [
      {
       "measurement": "ceph_osd_perf",
       "query": "SELECT \"commit_latency_ms\",\"apply_latency_ms\" FROM \"ceph_osd_perf\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY \"osd_id\"",
       "select": [
        [
         { "params": [ "osd_id" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "cluster_name", "operator": "=~", "value": "/^$cluster_name$/" }
       ]
      }
     ]
    },
    {
     "title": "Commit/Apply Latency (ceph osd perf)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Commit Latency",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"commit_latency_ms\") FROM \"ceph_osd_perf\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time(1m)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Apply Latency",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"apply_latency_ms\") FROM \"ceph_osd_perf\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time(1m)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 15, "y": 10 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"total_bytes\" FROM \"ceph_usage\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OSD Info (from ceph status)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Total OSDs",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"num_osds\") FROM \"ceph_osdmap\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time(1m)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Up OSDs",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"num_up_osds\") FROM \"ceph_osdmap\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time(1m)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "In OSDs",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"num_in_osds\") FROM \"ceph_osdmap\" WHERE (\"cluster_name\" =~ /^$cluster_name$/) AND $timeFilter GROUP BY time(1m)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx Logs Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upload Details",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "test_ceph_nginx_2",
       "query": "SELECT \"status\",\"request_length\",\"request_time\",\"remote_addr\",\"http_x_forwarded_for\",\"host_ip\",\"bucket\",\"file\"  FROM \"nginx_upload_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter LIMIT 500",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Download Details",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "test_ceph_nginx_2",
       "query": "SELECT \"status\",\"body_bytes_sent\",\"request_time\",\"remote_addr\",\"http_x_forwarded_for\",\"host_ip\",\"bucket\",\"file\" FROM \"nginx_download_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter LIMIT 500",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Delete Details",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "test_ceph_nginx_2",
       "query": "SELECT \"status\",\"request_time\",\"remote_addr\",\"http_x_forwarded_for\",\"host_ip\",\"bucket\",\"file\"  FROM \"nginx_delete_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter LIMIT 500",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Nginx Access Logs",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 102 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "test_ceph_nginx_2",
       "query": "SELECT \"status\",\"request_time\",\"remote_addr\",\"http_x_forwarded_for\",\"host_ip\",\"uri\"  FROM \"nginx_access_log\" WHERE \"cluster_name\" =~ /^$cluster_name$/ AND $timeFilter LIMIT 100",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}